/**
 * Diary Web App - Express Server
 * Connects to Airtable to display diaries and comments
 */

require('dotenv').config();
const express = require('express');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Airtable configuration
const AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY;
const BASE_ID = process.env.BASE_ID;
const AIRTABLE_BASE_URL = `https://api.airtable.com/v0/${BASE_ID}`;

// Middleware
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Helper function for Airtable API calls
async function airtableRequest(endpoint, options = {}) {
    const url = `${AIRTABLE_BASE_URL}${endpoint}`;
    const response = await fetch(url, {
        ...options,
        headers: {
            'Authorization': `Bearer ${AIRTABLE_API_KEY}`,
            'Content-Type': 'application/json',
            ...options.headers
        }
    });

    if (!response.ok) {
        const error = await response.text();
        throw new Error(`Airtable API error: ${response.status} - ${error}`);
    }

    return response.json();
}

// API: Get diaries for a visitor
app.get('/api/diaries', async (req, res) => {
    try {
        const { visitorId } = req.query;

        if (!visitorId) {
            return res.status(400).json({ error: 'visitorId is required' });
        }

        // Filter by VisitorID and sort by When descending
        const filterFormula = encodeURIComponent(`{VisitorID} = "${visitorId}"`);
        const endpoint = `/Diary?filterByFormula=${filterFormula}&sort[0][field]=When&sort[0][direction]=desc`;

        const data = await airtableRequest(endpoint);

        const diaries = data.records.map(record => ({
            id: record.id,
            diaryId: record.fields.DiaryID || record.id,
            content: record.fields['情绪日记'] || '',
            aiFeedback: record.fields['AI反馈'] || '',
            when: record.fields.When || ''
        }));

        res.json(diaries);
    } catch (error) {
        console.error('Error fetching diaries:', error);
        res.status(500).json({ error: error.message });
    }
});

// API: Get comments for a diary
app.get('/api/comments', async (req, res) => {
    try {
        const { diaryId } = req.query;

        if (!diaryId) {
            return res.status(400).json({ error: 'diaryId is required' });
        }

        console.log('Fetching comments for diaryId:', diaryId);

        // First, try without filter to see if table exists and has data
        // Then filter on client side
        const endpoint = `/Comments?sort[0][field]=Created&sort[0][direction]=asc`;
        console.log('API endpoint:', endpoint);

        const data = await airtableRequest(endpoint);
        console.log('Total comments in table:', data.records.length);

        // Debug: log first record structure
        if (data.records.length > 0) {
            console.log('First record fields:', JSON.stringify(data.records[0].fields, null, 2));
        }

        // Filter comments that match the diaryId
        const filteredRecords = data.records.filter(record => {
            const linkedDiaryIds = record.fields.Diary || [];
            // Diary is a linked record field (array of record IDs)
            if (Array.isArray(linkedDiaryIds)) {
                return linkedDiaryIds.includes(diaryId);
            }
            return linkedDiaryIds === diaryId;
        });

        console.log('Filtered comments count:', filteredRecords.length);

        const comments = filteredRecords.map(record => ({
            id: record.id,
            role: record.fields.Role || '',
            content: record.fields.Content || '',
            created: record.fields.Created || ''
        }));

        res.json(comments);
    } catch (error) {
        console.error('Error fetching comments:', error.message);
        res.status(500).json({ error: error.message });
    }
});

// API: Create a new comment
app.post('/api/comment', async (req, res) => {
    try {
        const { diaryId, visitorId, content } = req.body;

        if (!diaryId || !visitorId || !content) {
            return res.status(400).json({ error: 'diaryId, visitorId, and content are required' });
        }

        console.log('Creating comment:', { diaryId, visitorId, content });

        // Diary is a linked record field, so we pass it as an array of record IDs
        // Created field is auto-generated by Airtable (Created time type)
        // Role: empty = visitor, analyst = 咨询师
        const newRecord = {
            fields: {
                Diary: [diaryId],
                Content: content
            }
        };

        console.log('Sending to Airtable:', JSON.stringify(newRecord, null, 2));

        const data = await airtableRequest('/Comments', {
            method: 'POST',
            body: JSON.stringify(newRecord)
        });

        console.log('Airtable response:', JSON.stringify(data, null, 2));

        res.json({
            success: true,
            comment: {
                id: data.id,
                role: data.fields.Role || 'visitor',
                content: data.fields.Content || '',
                created: data.fields.Created || new Date().toISOString()
            }
        });
    } catch (error) {
        console.error('Error creating comment:', error);
        res.status(500).json({ error: error.message });
    }
});

// Serve index.html for all other routes
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Start server
app.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}`);
    console.log(`Example: http://localhost:${PORT}/?visitorId=A005`);
});
